# main menu
[[main]]
name = "Introduction"
url = "#banner"
pre = "fa-solid fa-user"
weight = -1

# [[main]]
# name = "My Skills"
# url = "#skill"
# pre = "fa-solid fa-list-check"
# weight = 2

[[main]]
name = "Courses"
url = "#courses"
pre = "fa-solid fa-school"
weight = 2

# [[main]]
# name = "Resume"
# url = "#resume"
# pre = "fa-solid fa-address-card"
# weight = 3

[[main]]
name = "Articles"
url = "#blog"
pre = "fa-solid fa-newspaper"
weight = 3

[[main]]
name = "Notes"
url = "notes"
pre = "fa-solid fa-note-sticky"
weight = 4

# [[main]]
# name = "Projects"
# url = "#projects"
# pre = "fa-solid fa-box"
# weight = 4

# [[main]]
# name = "Contact"
# url = "#contact"
# pre = "fa-solid fa-paper-plane"
# weight = 6
