# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#18b0a2"
color_secondary = "#151923"
body_color = "#0e1015"
text_color = "#bbb"
text_dark = "#222222"
text_light = "#959595"
border_color = "rgba($color-primary, 0.15)"

light_body_color = "#FFFFFF"
light_text_color = "#555"
light_border_color = "#ddd"
light_color_secondary = "#f6f6f6"
light_text_light = "#959595"
light_text_dark = "#222222"

black = "#191f27"
white = "#fff"
dark = "#222"
light = "#eee"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.26" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Poppins:wght@200;300;400;500;600"
font_primary_type = "sans-serif"                  # [serif/sans-serif]
font_secondary = ""
font_secondary_type = ""                          # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"                 # https://fontawesome.com/v6.0/icons/


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
[[params.plugins.css]]
link = "plugins/aos/aos.custom.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
# [[params.plugins.js]]
# link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
# attributes = "async"
